version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "lockfile-only"
    groups:
      dependencies:
        patterns:
          - "*" # Update all packages together
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
